config/routes.rb
BrewingDiary::Application.routes.draw do
  

  get "/homebrew_guide" => "homebrew_guide#index"
  get "/contact_us" => "contact_us#index"
  get "/about_us" => "about_us#index"

  resources :brew_types

  resources :readings
  resources :brewings do
    get "set_bottled" => "brewings#set_bottled", :as => "set_bottled"
    get "set_ready" => "brewings#set_ready", :as => "set_ready"
    post :rate, :on => :member
  end
  
  devise_for :users

  root :to => "welcome#index"

end

app/models/reading.rb
class Reading < ActiveRecord::Base

  belongs_to :brewing
  
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  # GET /readings
  # GET /readings.xml
  def index
    @readings = Reading.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @readings }
    end
  end

  # GET /readings/1
  # GET /readings/1.xml
  def show
    @reading = Reading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reading }
    end
  end

  # GET /readings/new
  # GET /readings/new.xml
  def new
    @reading = Reading.new
    unless params[:brewing_id].nil?
      @reading.brewing = Brewing.find(params[:brewing_id])
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reading }
    end
  end

  # GET /readings/1/edit
  def edit
    @reading = Reading.find(params[:id])
  end

  # POST /readings
  # POST /readings.xml
  def create
    @reading = Reading.new(params[:reading])
    
    respond_to do |format|
      if @reading.save
        format.html { redirect_to(@reading.brewing, :notice => 'Reading was successfully created.') }
        format.xml  { render :xml => @reading, :status => :created, :location => @reading }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reading.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /readings/1
  # PUT /readings/1.xml
  def update
    @reading = Reading.find(params[:id])

    respond_to do |format|
      if @reading.update_attributes(params[:reading])
        format.html { redirect_to(@reading.brewing, :notice => 'Reading was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reading.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.xml
  def destroy
    @reading = Reading.find(params[:id])
    brewing = @reading.brewing
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to(brewing) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.haml
= simple_form_for @reading do |f|
  -if @reading.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reading.errors.count, "error")} prohibited this reading from being saved:"
      %ul
        - @reading.errors.full_messages.each do |msg|
          %li= msg

  = f.association :brewing
  = f.input :taken_on
  = f.input :temperature, :as => :string
  = f.input :specific_gravity
  .clear
  = f.button :submit

app/views/readings/edit.html.haml
%h1 Editing reading

= render 'form'

= link_to 'Show', @reading
\|
= link_to 'Back', readings_path

app/views/readings/index.html.haml
%h1 Listing readings

%table
  %tr
    %th Brewing
    %th Temperature
    %th Specific gravity
    %th
    %th
    %th

  - @readings.each do |reading|
    %tr
      %td= link_to reading.brewing.name, reading.brewing
      %td= reading.temperature
      %td= reading.specific_gravity
      %td= link_to 'Show', reading
      %td= link_to 'Edit', edit_reading_path(reading)
      %td= link_to 'Destroy', reading, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Reading', new_reading_path

app/views/readings/new.html.haml
%h1 New reading

= render 'form'

= link_to 'Back', brewings_path

app/views/readings/show.html.haml
%p#notice= notice

%p
  %b Temperature:
  = @reading.temperature
%p
  %b Specific gravity:
  = @reading.specific_gravity

= link_to 'Edit', edit_reading_path(@reading)
\|
= link_to 'Back', readings_path