config/routes.rb
BrewingDiary::Application.routes.draw do
  

  get "/homebrew_guide" => "homebrew_guide#index"
  get "/contact_us" => "contact_us#index"
  get "/about_us" => "about_us#index"

  resources :brew_types

  resources :readings
  resources :brewings do
    get "set_bottled" => "brewings#set_bottled", :as => "set_bottled"
    get "set_ready" => "brewings#set_ready", :as => "set_ready"
    post :rate, :on => :member
  end
  
  devise_for :users

  root :to => "welcome#index"

end

app/controllers/brew_types_controller.rb
class BrewTypesController < ApplicationController
  # GET /brew_types
  # GET /brew_types.xml
  def index
    @brew_types = BrewType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @brew_types }
    end
  end

  # GET /brew_types/1
  # GET /brew_types/1.xml
  def show
    @brew_type = BrewType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @brew_type }
    end
  end

  # GET /brew_types/new
  # GET /brew_types/new.xml
  def new
    @brew_type = BrewType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @brew_type }
    end
  end

  # GET /brew_types/1/edit
  def edit
    @brew_type = BrewType.find(params[:id])
  end

  # POST /brew_types
  # POST /brew_types.xml
  def create
    @brew_type = BrewType.new(params[:brew_type])

    respond_to do |format|
      if @brew_type.save
        format.html { redirect_to(@brew_type, :notice => 'Brew type was successfully created.') }
        format.xml  { render :xml => @brew_type, :status => :created, :location => @brew_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @brew_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /brew_types/1
  # PUT /brew_types/1.xml
  def update
    @brew_type = BrewType.find(params[:id])

    respond_to do |format|
      if @brew_type.update_attributes(params[:brew_type])
        format.html { redirect_to(@brew_type, :notice => 'Brew type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @brew_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /brew_types/1
  # DELETE /brew_types/1.xml
  def destroy
    @brew_type = BrewType.find(params[:id])
    @brew_type.destroy

    respond_to do |format|
      format.html { redirect_to(brew_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/brew_types_helper.rb
module BrewTypesHelper
end

app/views/brew_types/_form.html.haml
= form_for @brew_type do |f|
  -if @brew_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@brew_type.errors.count, "error")} prohibited this brew_type from being saved:"
      %ul
        - @brew_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/brew_types/edit.html.haml
%h1 Editing brew_type

= render 'form'

= link_to 'Show', @brew_type
\|
= link_to 'Back', brew_types_path

app/views/brew_types/index.html.haml
%h1 Listing brew_types

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @brew_types.each do |brew_type|
    %tr
      %td= brew_type.name
      %td= link_to 'Show', brew_type
      %td= link_to 'Edit', edit_brew_type_path(brew_type)
      %td= link_to 'Destroy', brew_type, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Brew type', new_brew_type_path

app/views/brew_types/new.html.haml
%h1 New brew_type

= render 'form'

= link_to 'Back', brew_types_path

app/views/brew_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @brew_type.name

= link_to 'Edit', edit_brew_type_path(@brew_type)
\|
= link_to 'Back', brew_types_path