config/routes.rb
BrewingDiary::Application.routes.draw do
  

  get "/homebrew_guide" => "homebrew_guide#index"
  get "/contact_us" => "contact_us#index"
  get "/about_us" => "about_us#index"

  resources :brew_types

  resources :readings
  resources :brewings do
    get "set_bottled" => "brewings#set_bottled", :as => "set_bottled"
    get "set_ready" => "brewings#set_ready", :as => "set_ready"
    post :rate, :on => :member
  end
  
  devise_for :users

  root :to => "welcome#index"

end

app/models/brewing.rb
class Brewing < ActiveRecord::Base

  ajaxful_rateable :stars => 5, :allow_update => true

  has_many :readings
  belongs_to :user
  belongs_to :brew_type

  default_scope order("ferment_started_on ASC")
  scope :current, lambda {where("ready_on >= ?", DateTime.now)}
  scope :past, lambda {where("ready_on < ?", DateTime.now)}
  scope :for, lambda {|user| where("user_id = ?", user.id)}


  def estimate_bottled_on
    if self.readings.count > 4
      hourly_rate_of_change = get_rate
      change = (self.readings[0].specific_gravity - self.readings[1].specific_gravity) / ((self.readings[1].taken_on - self.readings[0].taken_on) / 60 / 60)
  
      hour = 0
      safety_valve = 0
      while change > 0 or safety_valve > 720
        hour += 1
        change = change - hourly_rate_of_change
        safety_valve += 1
      end
      self.ferment_started_on + hour.hours
    end
  end
  
  def show_state
    if state == "PRIMARY"
      "in Primary Fermentation"
    elsif state == "SECONDARY"
      "in Secondary Fermentation"
    elsif state == "READY"
      "Ready for consumption!"
    else
      nil
    end
  end

  private
  
  def get_rate
    changes = calculate_changes
    average_rate = changes.inject{ |sum, el| sum + el }.to_f / changes.size
    average_rate / ((self.readings[1].taken_on - self.readings[0].taken_on) / 60 / 60)
  end

  def calculate_changes
    last_rate = nil
    changes = (0...self.readings.count).map do |i|
      if i > 0
        last_reading = self.readings[i-1]
        reading = self.readings[i]
        hours = (reading.taken_on - last_reading.taken_on) / 60 / 60
        change = last_reading.specific_gravity - reading.specific_gravity
        rate_of_change = change / hours
        diff = last_rate - rate_of_change unless last_rate.nil?
        last_rate = rate_of_change
        diff
      end
    end
    changes.reject{|c| c.nil?}
  end
  
end

app/controllers/brewings_controller.rb
class BrewingsController < ApplicationController
  # GET /brewings
  # GET /brewings.xml

  before_filter :authenticate_user!  
  
  def index
    @brewings = Brewing.all
    
    @current_brewings = Brewing.current.for(current_user)
    @past_brewings = Brewing.past.for(current_user)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @brewings }
    end
  end

  # GET /brewings/1
  # GET /brewings/1.xml
  def show
    @brewing = Brewing.find(params[:id])

    if @brewing.ready_on < DateTime.now
      @brewing.update_attributes(:state => "READY")
    end    
    
    redirect_to "/" unless @brewing.user.id == current_user.id or current_user.admin?

    @t_graph = HighChart.new('temperature') do |f|
      f.options[:chart][:defaultSeriesType] = "line"
      f.options[:chart][:backgroundColor] = "#1d1d1d"
      f.options[:title][:text] = "Temperature Readings"
      f.options[:legend][:enabled] = false
      f.series(:name=>'Temperature', :data=>@brewing.readings.map{|r|[r.taken_on.to_i*1000, r.temperature]})
      f.y_axis(:title => {:text => "Temperature C"})
      f.x_axis(:type => "datetime", :title => {:text => "Date Taken On"}, :dateTimeLabelFormats => {:month => '%e %b', :year => '%b'})
      #f.options[:x_axis][:categories] = @brewing.readings.map{|r| friendly_date(r.taken_on)}
  
    end
    @sg_graph = HighChart.new('specific_gravity') do |f|
      f.options[:chart][:defaultSeriesType] = "line"
      f.options[:chart][:backgroundColor] = "#1d1d1d"
      f.options[:title][:text] = "Specific Gravity Readings"
      f.options[:legend][:enabled] = false
      f.y_axis(:title => {:text => "Specific Gravity"})
      f.x_axis(:type => "datetime", :title => {:text => "Date Taken On"}, :dateTimeLabelFormats => {:month => '%e %b', :year => '%b'})
      f.series(:name=>'Specific Gravity', :data=> @brewing.readings.map{|r| [r.taken_on.to_i*1000, r.specific_gravity]} )
      #f.options[:x_axis][:categories] = @brewing.readings.map{|r| friendly_date(r.taken_on)}
      
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @brewing }
    end
  end

  # GET /brewings/new
  # GET /brewings/new.xml
  def new
    @brewing = Brewing.new
    @brewing.user_id = current_user.id
    @brewing.bottled_on = Date.today + 7.days
    @brewing.ready_on = Date.today + 5.weeks

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @brewing }
    end
  end

  # GET /brewings/1/edit
  def edit
    @brewing = Brewing.find(params[:id])
  end

  # POST /brewings
  # POST /brewings.xml
  def create
    @brewing = Brewing.new(params[:brewing])
    @brewing.user = current_user
    @brewing.state = "PRIMARY"

    respond_to do |format|
      if @brewing.save
        format.html { redirect_to(@brewing, :notice => 'Brewing was successfully created.') }
        format.xml  { render :xml => @brewing, :status => :created, :location => @brewing }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @brewing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /brewings/1
  # PUT /brewings/1.xml
  def update
    @brewing = Brewing.find(params[:id])

    respond_to do |format|
      if @brewing.update_attributes(params[:brewing])
        format.html { redirect_to(@brewing, :notice => 'Brewing was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @brewing.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def set_bottled
    @brewing = Brewing.find(params[:brewing_id])
    @brewing.state = "SECONDARY"
    @brewing.bottled_on = DateTime.now
    @brewing.ready_on = DateTime.now + 4.weeks
    @brewing.save
    
    redirect_to @brewing
  end

  def set_ready
    @brewing = Brewing.find(params[:brewing_id])
    @brewing.state = "READY"
    @brewing.ready_on = DateTime.now
    @brewing.save
    
    redirect_to @brewing
  end
  
  def rate
    @brewing = Brewing.find(params[:id])
    @brewing.rate(params[:stars], current_user, params[:dimension])
    average = @brewing.rate_average(true, params[:dimension])
    width = (average / @brewing.class.max_stars.to_f) * 100
    render :json => {:id => @brewing.wrapper_dom_id(params), :average => average, :width => width}
  end


  # DELETE /brewings/1
  # DELETE /brewings/1.xml
  def destroy
    @brewing = Brewing.find(params[:id])
    @brewing.destroy

    respond_to do |format|
      format.html { redirect_to(brewings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/brewings_helper.rb
module BrewingsHelper

  def date_in_words(date)
    if date > DateTime.now - 7.days
      words = ""
      words += "in " if date > DateTime.now
      words += time_ago_in_words(date).strip
      words += " ago" if date < DateTime.now
      words
    else
      "#{date.day.ordinalize} #{date.strftime("%B %Y")}"
    end
  end
  
end

app/views/brewings/_form.html.haml
= simple_form_for @brewing do |f|
  -if @brewing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@brewing.errors.count, "error")} prohibited this brewing from being saved:"
      %ul
        - @brewing.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name
  - if current_user.admin? 
    = f.input :state
  = f.input :ferment_started_on
  = f.input :bottled_on
  = f.input :ready_on
  = f.input :quantity, :label => "Quantity (Litres)"
  = f.input :notes
  = f.association :brew_type, :collection => BrewType.all(:order => "name"), :include_blank => false
  = f.input :kit_name
  .clear
  = f.button :submit

app/views/brewings/edit.html.haml
%h1 Editing brewing

= render 'form'

= link_to 'Show', @brewing
\|
= link_to 'Back', brewings_path

app/views/brewings/index.html.haml
#brewings-index
  %h1 Current brewings
  - if @current_brewings.empty?
    = "You don't have any current brewings" 
  - @current_brewings.each do |brewing|
    = "#{brewing.ferment_started_on}"
    = " - "
    = link_to brewing.name, brewing
  
  
  %h1 Past brewings
  - if @past_brewings.empty?
    = "You don't have any past brewings" 
  - @past_brewings.each do |brewing|
    = link_to brewing.name, brewing
    = " - Started on #{brewing.ferment_started_on}"
  
  %h2
    = link_to 'start a new brewing', new_brewing_path

app/views/brewings/new.html.haml
%h1 New brewing

= render 'form'

= link_to 'Back', brewings_path

app/views/brewings/show.html.haml
.new-reading
  = link_to "add a new reading", new_reading_path(:brewing_id => @brewing.id)
  - if @brewing.state == "PRIMARY"
    %br
    = link_to "bottled yet?", brewing_set_bottled_path(:brewing_id => @brewing.id)
  - if @brewing.state == "SECONDARY"
    %br
    = link_to "ready yet?", brewing_set_ready_path(:brewing_id => @brewing.id)
  %br
  = link_to "edit this brewing", edit_brewing_path(@brewing)

%h1= @brewing.name
- unless @brewing.show_state.nil?
  Currently #{@brewing.show_state}
  
- if @brewing.state == "READY"
  %br
  Give it a rating 
  = ratings_for @brewing, :size => "medium"

- if @brewing.state == "PRIMARY"
  :css
    .date-box {margin-left: 60px;}

.clear
#dashboard
  #dashboard-top
    .date-box#started
      .box-title Started
      .box-value
        = date_in_words(@brewing.ferment_started_on)
    .date-box
      .box-title #{@brewing.bottled_on > DateTime.now ? "Bottle" : "Bottled"}
      .box-value
        = date_in_words(@brewing.bottled_on)
    - if @brewing.state == "PRIMARY"
      .date-box
        .box-title Estimated
        .box-value
          - if @brewing.estimate_bottled_on.nil?
            No data yet
          - else        
            = date_in_words(@brewing.estimate_bottled_on)
    .date-box
      .box-title Ready
      .box-value
        = date_in_words(@brewing.ready_on)
    .date-box
      .box-title Quantity
      .box-value
        = "#{@brewing.quantity} Litres (#{number_with_precision(@brewing.quantity * 1.75975398639, :precision => 0)} Pints)"
  
    .clear 
  #dashboard-bottom
  
    %h3 Notes:
    = @brewing.notes
    %h3 Kit name:
    = @brewing.kit_name
  
  
%h2 Charts
.graph
  = high_chart("tgraph", @t_graph)
.graph
  = high_chart("sggraph", @sg_graph)

.clear
%h2 Readings
.readings  
  %table
    %tr
      %th Date
      %th Temperature (C)
      %th Specific gravity
      %th
      %th
      %th
  
    - @brewing.readings.each do |reading|
      %tr
        %td= reading.taken_on.strftime("%d %B %Y  %H:%M")
        %td= reading.temperature
        %td= reading.specific_gravity
        %td= link_to 'Edit', edit_reading_path(reading)
        %td= link_to 'Delete', reading, :confirm => 'Are you sure?', :method => :delete  


  
= link_to 'Edit', edit_brewing_path(@brewing)
\|
= link_to 'Back', brewings_path